### ISSUE TITLE
Pre-encoded checkpoints empty

### ISSUE THREAD

**Issue by RuochenZhao** [facebookresearch/tart#1]
The provided embedding folder in Readme.md is empty:

[here](https://drive.google.com/drive/folders/17Pxuu2cgLD8Sqci4SmOA1Oq5dxRNPNcu?usp=sharing)

**Comment by AkariAsai** [comment]
Hi! Sorry for my late response, I uploaded all of the embeddings for the BEIR datasets generted by our TART-dual at [embeddings_inst_dpr.zip](https://homes.cs.washington.edu/~akari/embeddings_inst_dpr.zip).

**Comment by AkariAsai** [comment]
I am closing this issue. Thanks!
