### ISSUE TITLE
When do you release a script for BERRI?

### ISSUE THREAD

**Issue by DaehanKim** [facebookresearch/tart#2]
@AkariAsai, thank you for this awesome work! 
I wonder when BERRI dataset script becomes available.
Thanks!

**Comment by AkariAsai** [comment]
Hi sorry for my late response! I'm working on the script and the preprocessed data by the third party (for some legal reasons, Meta cannot directly release the data) will be available together. Thanks for your patient!

**Comment by AkariAsai** [comment]
Hi, I uploaded odes on BERRI preprocessing at [BERRI](https://github.com/facebookresearch/tart/blob/main/BERRI), and more details are in [README.md](https://github.com/facebookresearch/tart/blob/main/BERRI/README.md). Let me know if you have any followup questions!

**Comment by DaehanKim** [comment]
Thank you for releasing the script! I'll take a look.
