### ISSUE TITLE
task_to_keys is not defined in finetuning_tart_full.py

### ISSUE THREAD

**Issue by DaehanKim** [facebookresearch/tart#5]
Hi @AkariAsai 
I'm trying to finetune tart-full and found variable `task_to_keys` is not found.
In your example command, `--task_name ce` is specified, but I cannot see what this abbreviation means.
I also saw `BERRI/berri_instructions.tsv`, but no abbreviation is found here. Can you please explain? Thank you.

**Comment by DaehanKim** [comment]
I just deleted corresponding line and everything works well thanks.

**Comment by AkariAsai** [comment]
Hi thank you so much for reporting the issue, I will fix the script!
