### ISSUE TITLE
Encoded embeddings link is a 404

### ISSUE THREAD

**Issue by vmajor** [facebookresearch/tart#6]
In this passage in the [README.md](https://github.com/facebookresearch/tart#readme): "Due to the larger corpus, we highly recommend encoding every documents beforehand. Encoded documents are available at the [encoded documents](https://github.com/facebookresearch/tart/blob/main/embeddings) Section."

The GitHub link is a 404.

**Comment by AkariAsai** [comment]
Thank you for reporting! I fixed the README link errors. The encoded embeddings are available at this google drive [link](https://drive.google.com/file/d/1qLqFLlvLpQ2OGHowO0Jwv_di8mJgh2be/view).
